import { Unit, UnitProps } from "js-ballistics/dist/v2";
import { MeasureFormFieldProps } from "./measureField";

export const measureFieldsProps: Record<string, Partial<MeasureFormFieldProps>> = {
    weight: {
        key: "weight",
        label: "Weight",
        suffix: UnitProps[Unit.Grain].symbol,
        icon: "weight",
        maxValue: 1000,
        minValue: 0,
        fractionDigits: 1,
        value: 15,
    },
    length: {
        key: "length",
        label: "Length",
        suffix: UnitProps[Unit.Inch].symbol,
        icon: "arrow-expand-horizontal",
        maxValue: 5,
        minValue: 0,
        fractionDigits: 2,
        value: 1.7,
    },
    temp: {
        key: "cZeroAirTemperature",
        label: "Temperature",
        suffix: UnitProps[Unit.Celsius].symbol,
        icon: "thermometer",
        maxValue: 50,
        minValue: -50,
        fractionDigits: 0,
        value: 15,
    },
    pressure: {
        key: "pressure",
        label: "Pressure",
        suffix: UnitProps[Unit.hPa].symbol,
        icon: "speedometer",
        maxValue: 1300,
        minValue: 700,
        fractionDigits: 0,
        value: 1000,
    },
    humidity: {
        key: "humidity",
        label: "Humidity",
        suffix: "%",
        icon: "water",
        maxValue: 100,
        minValue: 0,
        fractionDigits: 0,
        value: 78,
    },
    // altitude: {
    //     key: "altitude",
    //     label: "Altitude",
    //     suffix: UnitProps[Unit.Meter].symbol,
    //     icon: "ruler",
    //     maxValue: 3000,
    //     minValue: 0,
    //     decimals: 0,
    //     value: 150,
    // },
    lookAngle: {
        key: "cZeroWPitch",
        label: "Look angle",
        suffix: UnitProps[Unit.Degree].symbol,
        icon: "angle-acute",
        maxValue: 90,
        minValue: -90,
        fractionDigits: 1,
        value: 0,
        step: 0.1
    },
    windSpeed: {
        key: "windSpeed",
        label: "Wind speed",
        suffix: UnitProps[Unit.MPS].symbol,
        icon: "windsock",
        value: 0,
        maxValue: 100,
        minValue: 0,
        fractionDigits: 1,
        step: 0.1
    },
    muzzleVelocity: {
        key: "cMuzzleVelocity",
        label: "Muzzle velocity",
        suffix: UnitProps[Unit.MPS].symbol,
        icon: "speedometer",
        value: 0,
        maxValue: 2000,
        minValue: 10,
        fractionDigits: 0,
    },
    powderSens: {
        key: "cTCoeff",
        label: "Temperature sens.",
        suffix: "%/15°C",
        icon: "percent",
        value: 0,
        maxValue: 5,
        minValue: 0,
        fractionDigits: 2,
    },
    caliber: {
        key: "bDiameter",
        label: "Caliber",
        // suffix: UnitProps[Unit.Inch].symbol,
        icon: "diameter-variant",
        maxValue: 22,
        minValue: 0.001,
        fractionDigits: 3,
        step: 0.001,
        value: 0,
    },
    sightHeight: {
        key: "scHeight",
        label: "Sight height",
        icon: "crosshairs",
        fractionDigits: 1,
        value: 0,
    },
    twist: {
        key: "rTwist",
        label: "Twist",
        // suffix: UnitProps[Unit.Inch].symbol,
        icon: "screw-flat-top",
    },
};